Supress unnecessary GCC warning
Avoid warning for missing initializer:

source/common.c:156:5: error: missing initializer for field ‘pwm_mux_mode’ of ‘pins_t’ [-Werror=missing-field-initializers]
     { NULL, NULL, 0 }
     ^
source/common.c:54:9: note: ‘pwm_mux_mode’ declared here
     int pwm_mux_mode;
         ^
source/common.c:173:3: error: missing initializer for field ‘rx’ of ‘uart_t’ [-Werror=missing-field-initializers]
   { NULL, NULL, 0 }
   ^
source/common.c:163:17: note: ‘rx’ declared here
     const char *rx;